export const API_ACTION = "API_ACTION";

export const RECIPES = "RECIPES";
export const RECIPES_REQUESTED = "RECIPES_REQUESTED";
export const RECIPES_RECEIVED = "RECIPES_RECEIVED";
export const RECIPES_FAILED = "RECIPES_FAILED";
